### ISSUE TITLE
Integration of files bundle

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-instance#164]
## Use case

1. User creates a record. The response contains link in json serialization to bucket /records/1/files/.
2. User uploads a file to the bucket via PUT (binary stream)
3. User can now view the files in the API:
   - Records serialization
   - Bucket endpoint
4. User can now view files in the UI:
  - Record landing page should list files
  - Landing pages should include a preview.

## Tasks (incomplete):

- [x] Bucket should be created when the record is created (internally there should be a nice error message when a location is missing)
- [x] Record serializers needs to be changed to include files (from ``_files``) as well as a link to the bucket in ``links``. (https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/172)
- [x] Example documentation (for inveniosoftware.org and invenio quickstart needs to be created) (already defined in https://github.com/inveniosoftware/invenio/issues/3968)
- [x] Templates for records landing page must be created, that list the files and includes a previewer. (already defined in #175, #173)
- [x] Default location has to be created during setup (#165)
- [x] JSONSchema and ES Mappings have to support ``_files`` property and probably a ``_bucket`` property. (blocked by https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/177, already defined in https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/174)

**Comment by roksys** [comment]
The third bullet is done. I think it can be closed.
